#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import json
import requests
from typing import Dict, Any, Optional
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

class WebhookNotifier:
    """
    Send notifications to webhook endpoints
    """
    
    def __init__(self):
        self.webhook_url = os.getenv("WEBHOOK_URL")
        if not self.webhook_url:
            print("Warning: WEBHOOK_URL environment variable not set")
            
    def notify(self, event_type: str, data: Dict[str, Any]) -> bool:
        """
        Send a notification to the webhook
        
        Args:
            event_type: Type of event (content_generated, video_created, etc.)
            data: Event data to send
                
        Returns:
            True if notification was sent successfully, False otherwise
        """
        if not self.webhook_url:
            print("Cannot send webhook: URL not configured")
            return False
            
        try:
            # Prepare the payload
            payload = {
                "event_type": event_type,
                "timestamp": int(__import__("time").time()),
                "data": data
            }
            
            # Send the webhook
            response = requests.post(
                self.webhook_url,
                json=payload,
                headers={"Content-Type": "application/json"}
            )
            
            if response.status_code >= 200 and response.status_code < 300:
                print(f"Webhook notification sent successfully: {event_type}")
                return True
            else:
                print(f"Failed to send webhook: {response.status_code} - {response.text}")
                return False
                
        except Exception as e:
            print(f"Exception sending webhook: {str(e)}")
            return False

# Singleton instance
notifier = WebhookNotifier()

def send_notification(event_type: str, data: Dict[str, Any]) -> bool:
    """
    Send a notification via webhook
    
    Args:
        event_type: Type of event
        data: Event data
            
    Returns:
        True if notification was sent successfully, False otherwise
    """
    return notifier.notify(event_type, data)

def notify_content_generated(agent_id: str, content: str, trigger_id: str) -> bool:
    """
    Notify that content was generated by an agent
    
    Args:
        agent_id: ID of the agent that generated the content
        content: The generated content
        trigger_id: ID of the trigger that initiated the generation
            
    Returns:
        True if notification was sent successfully, False otherwise
    """
    data = {
        "agent_id": agent_id,
        "content": content,
        "trigger_id": trigger_id
    }
    
    return send_notification("content_generated", data)

def notify_video_created(agent_id: str, content: str, video_url: str, trigger_id: str) -> bool:
    """
    Notify that a video was created
    
    Args:
        agent_id: ID of the agent that generated the content
        content: The text content used to generate the video
        video_url: URL to the generated video
        trigger_id: ID of the trigger that initiated the generation
            
    Returns:
        True if notification was sent successfully, False otherwise
    """
    data = {
        "agent_id": agent_id,
        "content": content,
        "video_url": video_url,
        "trigger_id": trigger_id
    }
    
    return send_notification("video_created", data)

def notify_content_published(platform: str, content_id: str, url: str) -> bool:
    """
    Notify that content was published to a platform
    
    Args:
        platform: The platform where content was published (tiktok, twitter, etc.)
        content_id: ID of the content on the platform
        url: URL to the published content
            
    Returns:
        True if notification was sent successfully, False otherwise
    """
    data = {
        "platform": platform,
        "content_id": content_id,
        "url": url
    }
    
    return send_notification("content_published", data)

if __name__ == "__main__":
    # Example usage
    notify_content_generated(
        agent_id="trump-xbt",
        content="Bitcoin is doing TREMENDOUS things today. Many people are saying it's the BEST cryptocurrency!",
        trigger_id="rule-0"
    )
